//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JPSoftworks.MediaControlsExtension.Media.Vlc.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JPSoftworks.MediaControlsExtension.Media.Vlc.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to VLC denied HTTP access. Check its access rules for this computer and the configured password..
        /// </summary>
        internal static string Connection_AccessDenied {
            get {
                return ResourceManager.GetString("Connection_AccessDenied", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter an HTTP or HTTPS server URL with a valid port and no path or embedded password..
        /// </summary>
        internal static string Connection_InvalidEndpoint {
            get {
                return ResourceManager.GetString("Connection_InvalidEndpoint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to VLC returned invalid JSON. Check that this server URL belongs to VLC&apos;s HTTP interface..
        /// </summary>
        internal static string Connection_InvalidJson {
            get {
                return ResourceManager.GetString("Connection_InvalidJson", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The VLC observation was canceled..
        /// </summary>
        internal static string Connection_ObservationCanceled {
            get {
                return ResourceManager.GetString("Connection_ObservationCanceled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to VLC rejected the HTTP password. Check the password in VLC and the connection settings..
        /// </summary>
        internal static string Connection_PasswordRejected {
            get {
                return ResourceManager.GetString("Connection_PasswordRejected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter the VLC HTTP password in the connection settings..
        /// </summary>
        internal static string Connection_PasswordRequired {
            get {
                return ResourceManager.GetString("Connection_PasswordRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The VLC request was canceled; its outcome is unknown..
        /// </summary>
        internal static string Connection_RequestCanceled {
            get {
                return ResourceManager.GetString("Connection_RequestCanceled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to VLC connection settings changed..
        /// </summary>
        internal static string Connection_SettingsChanged {
            get {
                return ResourceManager.GetString("Connection_SettingsChanged", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to VLC did not respond in time. The provider will reconnect automatically..
        /// </summary>
        internal static string Connection_Timeout {
            get {
                return ResourceManager.GetString("Connection_Timeout", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot reach VLC. Check the server URL, Web interface, network access, and HTTPS certificate if used..
        /// </summary>
        internal static string Connection_Unreachable {
            get {
                return ResourceManager.GetString("Connection_Unreachable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to VLC returned an unknown playback state..
        /// </summary>
        internal static string Protocol_UnknownPlaybackState {
            get {
                return ResourceManager.GetString("Protocol_UnknownPlaybackState", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This provider requires the VLC 3 HTTP API (version 3)..
        /// </summary>
        internal static string Protocol_UnsupportedVersion {
            get {
                return ResourceManager.GetString("Protocol_UnsupportedVersion", resourceCulture);
            }
        }
    }
}