//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JPSoftworks.MediaControlsExtension.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JPSoftworks.MediaControlsExtension.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute.
        /// </summary>
        internal static string Command_Mute {
            get {
                return ResourceManager.GetString("Command_Mute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute system volume.
        /// </summary>
        internal static string Command_Mute_Subtitle {
            get {
                return ResourceManager.GetString("Command_Mute_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Application.
        /// </summary>
        internal static string Command_NextApp {
            get {
                return ResourceManager.GetString("Command_NextApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Track.
        /// </summary>
        internal static string Command_NextTrack {
            get {
                return ResourceManager.GetString("Command_NextTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip to the next track in the active media session.
        /// </summary>
        internal static string Command_NextTrack_Subtitle {
            get {
                return ResourceManager.GetString("Command_NextTrack_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string Command_Pause {
            get {
                return ResourceManager.GetString("Command_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string Command_Play {
            get {
                return ResourceManager.GetString("Command_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play / Pause.
        /// </summary>
        internal static string Command_PlayPause {
            get {
                return ResourceManager.GetString("Command_PlayPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Application.
        /// </summary>
        internal static string Command_PreviousApp {
            get {
                return ResourceManager.GetString("Command_PreviousApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Track.
        /// </summary>
        internal static string Command_PreviousTrack {
            get {
                return ResourceManager.GetString("Command_PreviousTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns to the previous track in the active media session.
        /// </summary>
        internal static string Command_PreviousTrack_Subtitle {
            get {
                return ResourceManager.GetString("Command_PreviousTrack_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string Command_Stop {
            get {
                return ResourceManager.GetString("Command_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to Application.
        /// </summary>
        internal static string Command_SwitchToApplication {
            get {
                return ResourceManager.GetString("Command_SwitchToApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Mute.
        /// </summary>
        internal static string Command_ToggleMute {
            get {
                return ResourceManager.GetString("Command_ToggleMute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Repeat.
        /// </summary>
        internal static string Command_ToggleRepeat {
            get {
                return ResourceManager.GetString("Command_ToggleRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Shuffle.
        /// </summary>
        internal static string Command_ToggleShuffle {
            get {
                return ResourceManager.GetString("Command_ToggleShuffle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmute.
        /// </summary>
        internal static string Command_Unmute {
            get {
                return ResourceManager.GetString("Command_Unmute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmute system volume.
        /// </summary>
        internal static string Command_Unmute_Subtitle {
            get {
                return ResourceManager.GetString("Command_Unmute_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No media sources are currently available. Please ensure that you have media applications running that support media controls..
        /// </summary>
        internal static string EmptyContent_Subtitle {
            get {
                return ResourceManager.GetString("EmptyContent_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No media sources available.
        /// </summary>
        internal static string EmptyContent_Title {
            get {
                return ResourceManager.GetString("EmptyContent_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage playback and switch between media apps with ease.
        /// </summary>
        internal static string MediaControls_Subtitle {
            get {
                return ResourceManager.GetString("MediaControls_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media controls.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing is playing right now.
        /// </summary>
        internal static string NowPlaying_NothingPlaying {
            get {
                return ResourceManager.GetString("NowPlaying_NothingPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now playing {0}.
        /// </summary>
        internal static string NowPlaying_NowPlaying {
            get {
                return ResourceManager.GetString("NowPlaying_NowPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause {0}.
        /// </summary>
        internal static string NowPlaying_Pause {
            get {
                return ResourceManager.GetString("NowPlaying_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play {0}.
        /// </summary>
        internal static string NowPlaying_Play {
            get {
                return ResourceManager.GetString("NowPlaying_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop {0}.
        /// </summary>
        internal static string NowPlaying_Stop {
            get {
                return ResourceManager.GetString("NowPlaying_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now playing.
        /// </summary>
        internal static string NowPlaying_Subtitle {
            get {
                return ResourceManager.GetString("NowPlaying_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search media commands or sessions….
        /// </summary>
        internal static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string Settings_GlobalCommands_Option_Disabled {
            get {
                return ResourceManager.GetString("Settings_GlobalCommands_Option_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string Settings_GlobalCommands_Option_Enabled {
            get {
                return ResourceManager.GetString("Settings_GlobalCommands_Option_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls additional media controls commands in the global search.
        /// </summary>
        internal static string Settings_GlobalCommands_Subtitle {
            get {
                return ResourceManager.GetString("Settings_GlobalCommands_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Commands.
        /// </summary>
        internal static string Settings_GlobalCommands_Title {
            get {
                return ResourceManager.GetString("Settings_GlobalCommands_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide after changing tracks.
        /// </summary>
        internal static string Settings_HideAfterChangingTracks {
            get {
                return ResourceManager.GetString("Settings_HideAfterChangingTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide after Play/Pause.
        /// </summary>
        internal static string Settings_HideAfterPlayPause {
            get {
                return ResourceManager.GetString("Settings_HideAfterPlayPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide after toggle play/pause on media session.
        /// </summary>
        internal static string Settings_HideAfterTogglePlayPause {
            get {
                return ResourceManager.GetString("Settings_HideAfterTogglePlayPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep the Command Palette open after running a command, so you can perform multiple actions in a row.
        ///Hold Shift while activating a command to temporarily do the opposite..
        /// </summary>
        internal static string Settings_KeepOpen_Subtitle {
            get {
                return ResourceManager.GetString("Settings_KeepOpen_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Command Palette open.
        /// </summary>
        internal static string Settings_KeepOpen_Title {
            get {
                return ResourceManager.GetString("Settings_KeepOpen_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When playing a session, automatically pause all other sessions..
        /// </summary>
        internal static string Settings_PauseOthersOnPlay_Subtitle {
            get {
                return ResourceManager.GetString("Settings_PauseOthersOnPlay_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause other sessions on play.
        /// </summary>
        internal static string Settings_PauseOthersOnPlay_Title {
            get {
                return ResourceManager.GetString("Settings_PauseOthersOnPlay_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds a “Now Playing” item to the home page for easy access to the current session..
        /// </summary>
        internal static string Settings_ShowCurrentMediaAtTopLevel_Subtitle {
            get {
                return ResourceManager.GetString("Settings_ShowCurrentMediaAtTopLevel_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show current media session on home page.
        /// </summary>
        internal static string Settings_ShowCurrentMediaAtTopLevel_Title {
            get {
                return ResourceManager.GetString("Settings_ShowCurrentMediaAtTopLevel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display “Next” and “Previous Track” as top-level items on the Media Controls page..
        /// </summary>
        internal static string Settings_ShowSkipCommands_Subtitle {
            get {
                return ResourceManager.GetString("Settings_ShowSkipCommands_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show skip track commands.
        /// </summary>
        internal static string Settings_ShowSkipCommands_Title {
            get {
                return ResourceManager.GetString("Settings_ShowSkipCommands_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display “Next” and “Previous Track” in the Dock..
        /// </summary>
        internal static string Settings_ShowSkipCommandsInDock_Subtitle {
            get {
                return ResourceManager.GetString("Settings_ShowSkipCommandsInDock_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show skip track commands in Dock.
        /// </summary>
        internal static string Settings_ShowSkipCommandsInDock_Title {
            get {
                return ResourceManager.GetString("Settings_ShowSkipCommandsInDock_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use media thumbnails (album art) instead of app icons in the session list..
        /// </summary>
        internal static string Settings_ShowThumbnails_Subtitle {
            get {
                return ResourceManager.GetString("Settings_ShowThumbnails_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show thumbnails.
        /// </summary>
        internal static string Settings_ShowThumbnails_Title {
            get {
                return ResourceManager.GetString("Settings_ShowThumbnails_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show a confirmation notification after each media action..
        /// </summary>
        internal static string Settings_ShowToastMessages_Subtitle {
            get {
                return ResourceManager.GetString("Settings_ShowToastMessages_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show toast messages.
        /// </summary>
        internal static string Settings_ShowToastMessages_Title {
            get {
                return ResourceManager.GetString("Settings_ShowToastMessages_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing.
        /// </summary>
        internal static string Tags_Playing {
            get {
                return ResourceManager.GetString("Tags_Playing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t change the volume.
        /// </summary>
        internal static string Toast_CantChangeVolume {
            get {
                return ResourceManager.GetString("Toast_CantChangeVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not change repeat mode.
        /// </summary>
        internal static string Toast_CouldNotChangeRepeat {
            get {
                return ResourceManager.GetString("Toast_CouldNotChangeRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not pause playback.
        /// </summary>
        internal static string Toast_CouldNotPause {
            get {
                return ResourceManager.GetString("Toast_CouldNotPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not play track.
        /// </summary>
        internal static string Toast_CouldNotPlay {
            get {
                return ResourceManager.GetString("Toast_CouldNotPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not skip to next track.
        /// </summary>
        internal static string Toast_CouldNotSkipNext {
            get {
                return ResourceManager.GetString("Toast_CouldNotSkipNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not go to previous track.
        /// </summary>
        internal static string Toast_CouldNotSkipPrevious {
            get {
                return ResourceManager.GetString("Toast_CouldNotSkipPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not switch to {0}: {1}.
        /// </summary>
        internal static string Toast_CouldNotSwitchTo {
            get {
                return ResourceManager.GetString("Toast_CouldNotSwitchTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not toggle shuffle.
        /// </summary>
        internal static string Toast_CouldNotToggleShuffle {
            get {
                return ResourceManager.GetString("Toast_CouldNotToggleShuffle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muted.
        /// </summary>
        internal static string Toast_Muted {
            get {
                return ResourceManager.GetString("Toast_Muted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No current media session found.
        /// </summary>
        internal static string Toast_NoCurrentSession {
            get {
                return ResourceManager.GetString("Toast_NoCurrentSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No next session found.
        /// </summary>
        internal static string Toast_NoNextSession {
            get {
                return ResourceManager.GetString("Toast_NoNextSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No other sessions to switch to.
        /// </summary>
        internal static string Toast_NoOtherSessions {
            get {
                return ResourceManager.GetString("Toast_NoOtherSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No media session manager found.
        /// </summary>
        internal static string Toast_NoSessionManager {
            get {
                return ResourceManager.GetString("Toast_NoSessionManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not the current session.
        /// </summary>
        internal static string Toast_NotCurrentSession {
            get {
                return ResourceManager.GetString("Toast_NotCurrentSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing happened.
        /// </summary>
        internal static string Toast_NothingHappened {
            get {
                return ResourceManager.GetString("Toast_NothingHappened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing is playing.
        /// </summary>
        internal static string Toast_NothingPlaying {
            get {
                return ResourceManager.GetString("Toast_NothingPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        internal static string Toast_Paused {
            get {
                return ResourceManager.GetString("Toast_Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing.
        /// </summary>
        internal static string Toast_Playing {
            get {
                return ResourceManager.GetString("Toast_Playing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing {0}.
        /// </summary>
        internal static string Toast_PlayingName {
            get {
                return ResourceManager.GetString("Toast_PlayingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat mode changed to {0}.
        /// </summary>
        internal static string Toast_RepeatChanged {
            get {
                return ResourceManager.GetString("Toast_RepeatChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat control is not available for this session.
        /// </summary>
        internal static string Toast_RepeatNotAvailable {
            get {
                return ResourceManager.GetString("Toast_RepeatNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuffle disabled.
        /// </summary>
        internal static string Toast_ShuffleDisabled {
            get {
                return ResourceManager.GetString("Toast_ShuffleDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuffle enabled.
        /// </summary>
        internal static string Toast_ShuffleEnabled {
            get {
                return ResourceManager.GetString("Toast_ShuffleEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuffle control is not available for this session.
        /// </summary>
        internal static string Toast_ShuffleNotAvailable {
            get {
                return ResourceManager.GetString("Toast_ShuffleNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped to next track.
        /// </summary>
        internal static string Toast_SkippedNext {
            get {
                return ResourceManager.GetString("Toast_SkippedNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returned to previous track.
        /// </summary>
        internal static string Toast_SkippedPrevious {
            get {
                return ResourceManager.GetString("Toast_SkippedPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switched to {0} and {1}.
        /// </summary>
        internal static string Toast_SwitchedTo {
            get {
                return ResourceManager.GetString("Toast_SwitchedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmuted.
        /// </summary>
        internal static string Toast_Unmuted {
            get {
                return ResourceManager.GetString("Toast_Unmuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Play / Pause.
        /// </summary>
        internal static string TogglePlayPause {
            get {
                return ResourceManager.GetString("TogglePlayPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play or pause current media.
        /// </summary>
        internal static string TogglePlayPause_Comments {
            get {
                return ResourceManager.GetString("TogglePlayPause_Comments", resourceCulture);
            }
        }
    }
}
