//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JPSoftworks.MediaControlsExtension.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JPSoftworks.MediaControlsExtension.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Mute.
        /// </summary>
        internal static string Command_Mute {
            get {
                return ResourceManager.GetString("Command_Mute", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Mute system volume.
        /// </summary>
        internal static string Command_Mute_Subtitle {
            get {
                return ResourceManager.GetString("Command_Mute_Subtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Next Application.
        /// </summary>
        internal static string Command_NextApp {
            get {
                return ResourceManager.GetString("Command_NextApp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Next Track.
        /// </summary>
        internal static string Command_NextTrack {
            get {
                return ResourceManager.GetString("Command_NextTrack", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Skip to the next track in the active media session.
        /// </summary>
        internal static string Command_NextTrack_Subtitle {
            get {
                return ResourceManager.GetString("Command_NextTrack_Subtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string Command_Pause {
            get {
                return ResourceManager.GetString("Command_Pause", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string Command_Play {
            get {
                return ResourceManager.GetString("Command_Play", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Play / Pause.
        /// </summary>
        internal static string Command_PlayPause {
            get {
                return ResourceManager.GetString("Command_PlayPause", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Previous Application.
        /// </summary>
        internal static string Command_PreviousApp {
            get {
                return ResourceManager.GetString("Command_PreviousApp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Previous Track.
        /// </summary>
        internal static string Command_PreviousTrack {
            get {
                return ResourceManager.GetString("Command_PreviousTrack", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Returns to the previous track in the active media session.
        /// </summary>
        internal static string Command_PreviousTrack_Subtitle {
            get {
                return ResourceManager.GetString("Command_PreviousTrack_Subtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Set volume to {0}%.
        /// </summary>
        internal static string Command_SetVolume {
            get {
                return ResourceManager.GetString("Command_SetVolume", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string Command_Stop {
            get {
                return ResourceManager.GetString("Command_Stop", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Switch to Application.
        /// </summary>
        internal static string Command_SwitchToApplication {
            get {
                return ResourceManager.GetString("Command_SwitchToApplication", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Toggle volume mute.
        /// </summary>
        internal static string Command_ToggleMute {
            get {
                return ResourceManager.GetString("Command_ToggleMute", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Toggle Repeat.
        /// </summary>
        internal static string Command_ToggleRepeat {
            get {
                return ResourceManager.GetString("Command_ToggleRepeat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Toggle Shuffle.
        /// </summary>
        internal static string Command_ToggleShuffle {
            get {
                return ResourceManager.GetString("Command_ToggleShuffle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unmute.
        /// </summary>
        internal static string Command_Unmute {
            get {
                return ResourceManager.GetString("Command_Unmute", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unmute system volume.
        /// </summary>
        internal static string Command_Unmute_Subtitle {
            get {
                return ResourceManager.GetString("Command_Unmute_Subtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to View full metadata.
        /// </summary>
        internal static string Command_ViewMetadata {
            get {
                return ResourceManager.GetString("Command_ViewMetadata", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Volume down.
        /// </summary>
        internal static string Command_VolumeDown {
            get {
                return ResourceManager.GetString("Command_VolumeDown", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Volume up.
        /// </summary>
        internal static string Command_VolumeUp {
            get {
                return ResourceManager.GetString("Command_VolumeUp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Album.
        /// </summary>
        internal static string Details_Album {
            get {
                return ResourceManager.GetString("Details_Album", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Album artist.
        /// </summary>
        internal static string Details_AlbumArtist {
            get {
                return ResourceManager.GetString("Details_AlbumArtist", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Application ID.
        /// </summary>
        internal static string Details_ApplicationId {
            get {
                return ResourceManager.GetString("Details_ApplicationId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        internal static string Details_Artist {
            get {
                return ResourceManager.GetString("Details_Artist", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Commands.
        /// </summary>
        internal static string Details_Commands {
            get {
                return ResourceManager.GetString("Details_Commands", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Genres.
        /// </summary>
        internal static string Details_Genres {
            get {
                return ResourceManager.GetString("Details_Genres", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        internal static string Details_Length {
            get {
                return ResourceManager.GetString("Details_Length", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Media type.
        /// </summary>
        internal static string Details_MediaType {
            get {
                return ResourceManager.GetString("Details_MediaType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string Details_MediaType_Image {
            get {
                return ResourceManager.GetString("Details_MediaType_Image", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        internal static string Details_MediaType_Music {
            get {
                return ResourceManager.GetString("Details_MediaType_Music", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Details_MediaType_Unknown {
            get {
                return ResourceManager.GetString("Details_MediaType_Unknown", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        internal static string Details_MediaType_Video {
            get {
                return ResourceManager.GetString("Details_MediaType_Video", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Not available.
        /// </summary>
        internal static string Details_NotAvailable {
            get {
                return ResourceManager.GetString("Details_NotAvailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Playback status.
        /// </summary>
        internal static string Details_PlaybackStatus {
            get {
                return ResourceManager.GetString("Details_PlaybackStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        internal static string Details_Player {
            get {
                return ResourceManager.GetString("Details_Player", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Provider.
        /// </summary>
        internal static string Details_Provider {
            get {
                return ResourceManager.GetString("Details_Provider", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Subtitle.
        /// </summary>
        internal static string Details_Subtitle {
            get {
                return ResourceManager.GetString("Details_Subtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Details_Title {
            get {
                return ResourceManager.GetString("Details_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Track.
        /// </summary>
        internal static string Details_TrackNumber {
            get {
                return ResourceManager.GetString("Details_TrackNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} of {1}.
        /// </summary>
        internal static string Details_TrackNumberWithCount {
            get {
                return ResourceManager.GetString("Details_TrackNumberWithCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No media sources are currently available. Please ensure that you have media applications running that support media controls..
        /// </summary>
        internal static string EmptyContent_Subtitle {
            get {
                return ResourceManager.GetString("EmptyContent_Subtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No media sources available.
        /// </summary>
        internal static string EmptyContent_Title {
            get {
                return ResourceManager.GetString("EmptyContent_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Manage playback and switch between media apps with ease.
        /// </summary>
        internal static string MediaControls_Subtitle {
            get {
                return ResourceManager.GetString("MediaControls_Subtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Available sessions.
        /// </summary>
        internal static string MediaSources_AvailableSessions {
            get {
                return ResourceManager.GetString("MediaSources_AvailableSessions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Configure.
        /// </summary>
        internal static string MediaSources_Configure {
            get {
                return ResourceManager.GetString("MediaSources_Configure", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        internal static string MediaSources_Connection {
            get {
                return ResourceManager.GetString("MediaSources_Connection", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        internal static string MediaSources_Connection_Connected {
            get {
                return ResourceManager.GetString("MediaSources_Connection_Connected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connecting.
        /// </summary>
        internal static string MediaSources_Connection_Connecting {
            get {
                return ResourceManager.GetString("MediaSources_Connection_Connecting", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        internal static string MediaSources_Connection_Disconnected {
            get {
                return ResourceManager.GetString("MediaSources_Connection_Disconnected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string MediaSources_Connection_Unknown {
            get {
                return ResourceManager.GetString("MediaSources_Connection_Unknown", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connection message.
        /// </summary>
        internal static string MediaSources_ConnectionMessage {
            get {
                return ResourceManager.GetString("MediaSources_ConnectionMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        internal static string MediaSources_Disable {
            get {
                return ResourceManager.GetString("MediaSources_Disable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string MediaSources_Disabled {
            get {
                return ResourceManager.GetString("MediaSources_Disabled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No matching media sources.
        /// </summary>
        internal static string MediaSources_Empty {
            get {
                return ResourceManager.GetString("MediaSources_Empty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        internal static string MediaSources_Enable {
            get {
                return ResourceManager.GetString("MediaSources_Enable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string MediaSources_Enabled {
            get {
                return ResourceManager.GetString("MediaSources_Enabled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to User setting.
        /// </summary>
        internal static string MediaSources_Enablement {
            get {
                return ResourceManager.GetString("MediaSources_Enablement", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Provider selection.
        /// </summary>
        internal static string MediaSources_ExclusiveSelection {
            get {
                return ResourceManager.GetString("MediaSources_ExclusiveSelection", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enabling this provider disables the other provider in its group. Switching waits for the previous provider to stop..
        /// </summary>
        internal static string MediaSources_ExclusiveSelectionDescription {
            get {
                return ResourceManager.GetString("MediaSources_ExclusiveSelectionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Provider status.
        /// </summary>
        internal static string MediaSources_Lifecycle {
            get {
                return ResourceManager.GetString("MediaSources_Lifecycle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string MediaSources_Lifecycle_Disabled {
            get {
                return ResourceManager.GetString("MediaSources_Lifecycle_Disabled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        internal static string MediaSources_Lifecycle_Faulted {
            get {
                return ResourceManager.GetString("MediaSources_Lifecycle_Faulted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string MediaSources_Lifecycle_Ready {
            get {
                return ResourceManager.GetString("MediaSources_Lifecycle_Ready", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Starting.
        /// </summary>
        internal static string MediaSources_Lifecycle_Starting {
            get {
                return ResourceManager.GetString("MediaSources_Lifecycle_Starting", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Stopping.
        /// </summary>
        internal static string MediaSources_Lifecycle_Stopping {
            get {
                return ResourceManager.GetString("MediaSources_Lifecycle_Stopping", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enable or disable media sources in Settings..
        /// </summary>
        internal static string MediaSources_Manage {
            get {
                return ResourceManager.GetString("MediaSources_Manage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select a media source to configure it, or use its command menu to enable or disable it..
        /// </summary>
        internal static string MediaSources_ManageProviders {
            get {
                return ResourceManager.GetString("MediaSources_ManageProviders", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} session.
        /// </summary>
        internal static string MediaSources_OneSession {
            get {
                return ResourceManager.GetString("MediaSources_OneSession", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open settings.
        /// </summary>
        internal static string MediaSources_OpenSettings {
            get {
                return ResourceManager.GetString("MediaSources_OpenSettings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Provider message.
        /// </summary>
        internal static string MediaSources_ProviderMessage {
            get {
                return ResourceManager.GetString("MediaSources_ProviderMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not save media source settings. Check access to the settings file and try again..
        /// </summary>
        internal static string MediaSources_SaveFailed {
            get {
                return ResourceManager.GetString("MediaSources_SaveFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search media sources.
        /// </summary>
        internal static string MediaSources_Search {
            get {
                return ResourceManager.GetString("MediaSources_Search", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} sessions.
        /// </summary>
        internal static string MediaSources_SessionCount {
            get {
                return ResourceManager.GetString("MediaSources_SessionCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connected to VLC. The saved connection settings work..
        /// </summary>
        internal static string MediaSources_TestConnected {
            get {
                return ResourceManager.GetString("MediaSources_TestConnected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Test saved connection.
        /// </summary>
        internal static string MediaSources_TestConnection {
            get {
                return ResourceManager.GetString("MediaSources_TestConnection", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not connect to VLC. Check its Web interface and the saved connection settings..
        /// </summary>
        internal static string MediaSources_TestFailed {
            get {
                return ResourceManager.GetString("MediaSources_TestFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to VLC connection settings changed during the test. Test the saved connection again..
        /// </summary>
        internal static string MediaSources_TestSettingsChanged {
            get {
                return ResourceManager.GetString("MediaSources_TestSettingsChanged", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Media sources.
        /// </summary>
        internal static string MediaSources_Title {
            get {
                return ResourceManager.GetString("MediaSources_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Album artwork.
        /// </summary>
        internal static string Metadata_ArtworkAltText {
            get {
                return ResourceManager.GetString("Metadata_ArtworkAltText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No media metadata is available..
        /// </summary>
        internal static string Metadata_NoMedia {
            get {
                return ResourceManager.GetString("Metadata_NoMedia", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Media metadata.
        /// </summary>
        internal static string Metadata_PageTitle {
            get {
                return ResourceManager.GetString("Metadata_PageTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Metadata.
        /// </summary>
        internal static string Metadata_Section {
            get {
                return ResourceManager.GetString("Metadata_Section", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Technical information.
        /// </summary>
        internal static string Metadata_TechnicalSection {
            get {
                return ResourceManager.GetString("Metadata_TechnicalSection", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Media Controls.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nothing is playing right now.
        /// </summary>
        internal static string NowPlaying_NothingPlaying {
            get {
                return ResourceManager.GetString("NowPlaying_NothingPlaying", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Now playing {0}.
        /// </summary>
        internal static string NowPlaying_NowPlaying {
            get {
                return ResourceManager.GetString("NowPlaying_NowPlaying", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pause {0}.
        /// </summary>
        internal static string NowPlaying_Pause {
            get {
                return ResourceManager.GetString("NowPlaying_Pause", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Play {0}.
        /// </summary>
        internal static string NowPlaying_Play {
            get {
                return ResourceManager.GetString("NowPlaying_Play", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Stop {0}.
        /// </summary>
        internal static string NowPlaying_Stop {
            get {
                return ResourceManager.GetString("NowPlaying_Stop", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Now playing.
        /// </summary>
        internal static string NowPlaying_Subtitle {
            get {
                return ResourceManager.GetString("NowPlaying_Subtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Media sessions.
        /// </summary>
        internal static string Page_Section_MediaSessions {
            get {
                return ResourceManager.GetString("Page_Section_MediaSessions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Playback.
        /// </summary>
        internal static string Page_Section_Playback {
            get {
                return ResourceManager.GetString("Page_Section_Playback", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remote sessions.
        /// </summary>
        internal static string Page_Section_RemoteSessions {
            get {
                return ResourceManager.GetString("Page_Section_RemoteSessions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to System volume.
        /// </summary>
        internal static string Page_Section_SystemVolume {
            get {
                return ResourceManager.GetString("Page_Section_SystemVolume", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        internal static string ReportProblem_DetailedLogging_Disable_Title {
            get {
                return ResourceManager.GetString("ReportProblem_DetailedLogging_Disable_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string ReportProblem_DetailedLogging_Disabled_Label {
            get {
                return ResourceManager.GetString("ReportProblem_DetailedLogging_Disabled_Label", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enable high-volume Debug and Trace entries in daily log files for this run only; the option resets on restart..
        /// </summary>
        internal static string ReportProblem_DetailedLogging_Disabled_Subtitle {
            get {
                return ResourceManager.GetString("ReportProblem_DetailedLogging_Disabled_Subtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        internal static string ReportProblem_DetailedLogging_Enable_Title {
            get {
                return ResourceManager.GetString("ReportProblem_DetailedLogging_Enable_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string ReportProblem_DetailedLogging_Enabled_Label {
            get {
                return ResourceManager.GetString("ReportProblem_DetailedLogging_Enabled_Label", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Daily log files include high-volume Debug and Trace entries until the option is disabled or the extension restarts..
        /// </summary>
        internal static string ReportProblem_DetailedLogging_Enabled_Subtitle {
            get {
                return ResourceManager.GetString("ReportProblem_DetailedLogging_Enabled_Subtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Detailed logging.
        /// </summary>
        internal static string ReportProblem_DetailedLogging_Title {
            get {
                return ResourceManager.GetString("ReportProblem_DetailedLogging_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to To report a problem:
        ///
        ///1. Reproduce the problem.
        ///2. Save the diagnostic logs to your Desktop.
        ///3. Open GitHub Issues and create a report.
        ///4. Attach the generated ZIP file to the report.
        ///
        ///Diagnostic logs can contain media titles, player names, and technical error details. Review the archive before sharing it..
        /// </summary>
        internal static string ReportProblem_Instructions {
            get {
                return ResourceManager.GetString("ReportProblem_Instructions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to GitHub Issues couldn&apos;t be opened. Try again or open the repository from Settings..
        /// </summary>
        internal static string ReportProblem_OpenGitHub_Failed {
            get {
                return ResourceManager.GetString("ReportProblem_OpenGitHub_Failed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Create a report and attach the diagnostic logs..
        /// </summary>
        internal static string ReportProblem_OpenGitHub_Subtitle {
            get {
                return ResourceManager.GetString("ReportProblem_OpenGitHub_Subtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open GitHub Issues.
        /// </summary>
        internal static string ReportProblem_OpenGitHub_Title {
            get {
                return ResourceManager.GetString("ReportProblem_OpenGitHub_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The diagnostic logs couldn&apos;t be saved. Check Command Palette diagnostics for details..
        /// </summary>
        internal static string ReportProblem_SaveLogs_Failed {
            get {
                return ResourceManager.GetString("ReportProblem_SaveLogs_Failed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Create a ZIP file to attach to a GitHub issue..
        /// </summary>
        internal static string ReportProblem_SaveLogs_Subtitle {
            get {
                return ResourceManager.GetString("ReportProblem_SaveLogs_Subtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Diagnostic logs were saved to your Desktop as {0}..
        /// </summary>
        internal static string ReportProblem_SaveLogs_Succeeded {
            get {
                return ResourceManager.GetString("ReportProblem_SaveLogs_Succeeded", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save diagnostic logs to Desktop.
        /// </summary>
        internal static string ReportProblem_SaveLogs_Title {
            get {
                return ResourceManager.GetString("ReportProblem_SaveLogs_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Report a problem.
        /// </summary>
        internal static string ReportProblem_Title {
            get {
                return ResourceManager.GetString("ReportProblem_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search media commands or sessions….
        /// </summary>
        internal static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remote.
        /// </summary>
        internal static string Session_Remote {
            get {
                return ResourceManager.GetString("Session_Remote", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Created by [Jiří Polášek](https://jiripolasek.com)
        ///_Licensed under the Apache 2.0 license_
        ///_Copyright © Jiří Polášek_
        ///
        ///Special thanks to [Mike Griese](https://github.com/zadjii-msft).
        /// </summary>
        internal static string Settings_Acknowledgements {
            get {
                return ResourceManager.GetString("Settings_Acknowledgements", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The saved selection for this group is invalid or conflicting. Choose one provider to repair it..
        /// </summary>
        internal static string Settings_Backend_ConflictingSelection {
            get {
                return ResourceManager.GetString("Settings_Backend_ConflictingSelection", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Three simulated players with random tracks and artwork. No audio is played..
        /// </summary>
        internal static string Settings_Backend_Dummy_Description {
            get {
                return ResourceManager.GetString("Settings_Backend_Dummy_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dummy media.
        /// </summary>
        internal static string Settings_Backend_Dummy_Title {
            get {
                return ResourceManager.GetString("Settings_Backend_Dummy_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Run Windows media sessions inside the extension for troubleshooting. Native Windows media failures can affect the extension..
        /// </summary>
        internal static string Settings_Backend_Gsmtc_Description {
            get {
                return ResourceManager.GetString("Settings_Backend_Gsmtc_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Windows media sessions (internal).
        /// </summary>
        internal static string Settings_Backend_Gsmtc_Title {
            get {
                return ResourceManager.GetString("Settings_Backend_Gsmtc_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Default Windows media provider. Run sessions in a separate process to isolate native Windows media failures. Selecting this provider replaces the internal provider..
        /// </summary>
        internal static string Settings_Backend_GsmtcWorker_Description {
            get {
                return ResourceManager.GetString("Settings_Backend_GsmtcWorker_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Windows media sessions (worker).
        /// </summary>
        internal static string Settings_Backend_GsmtcWorker_Title {
            get {
                return ResourceManager.GetString("Settings_Backend_GsmtcWorker_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The saved provider selection could not be read. Choose a provider again after checking the settings file..
        /// </summary>
        internal static string Settings_Backend_InvalidSavedSelection {
            get {
                return ResourceManager.GetString("Settings_Backend_InvalidSavedSelection", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not read saved media sources. They will be restored automatically when the settings file is readable. Choose a source to retry now..
        /// </summary>
        internal static string Settings_Backend_UnreadableSettings {
            get {
                return ResourceManager.GetString("Settings_Backend_UnreadableSettings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Control one local or remote VLC 3 player through its Web interface..
        /// </summary>
        internal static string Settings_Backend_Vlc_Description {
            get {
                return ResourceManager.GetString("Settings_Backend_Vlc_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to VLC media player.
        /// </summary>
        internal static string Settings_Backend_Vlc_Title {
            get {
                return ResourceManager.GetString("Settings_Backend_Vlc_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Choose icons for the Command Palette home page and Media Controls list page..
        /// </summary>
        internal static string Settings_CommandPaletteIconTheme_Subtitle {
            get {
                return ResourceManager.GetString("Settings_CommandPaletteIconTheme_Subtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Icon theme.
        /// </summary>
        internal static string Settings_CommandPaletteIconTheme_Title {
            get {
                return ResourceManager.GetString("Settings_CommandPaletteIconTheme_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Default (Switch to player).
        /// </summary>
        internal static string Settings_DockCurrentMediaAction_Option_Default {
            get {
                return ResourceManager.GetString("Settings_DockCurrentMediaAction_Option_Default", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open Media Controls.
        /// </summary>
        internal static string Settings_DockCurrentMediaAction_Option_OpenMediaControls {
            get {
                return ResourceManager.GetString("Settings_DockCurrentMediaAction_Option_OpenMediaControls", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open media metadata.
        /// </summary>
        internal static string Settings_DockCurrentMediaAction_Option_OpenMediaMetadata {
            get {
                return ResourceManager.GetString("Settings_DockCurrentMediaAction_Option_OpenMediaMetadata", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Switch to player.
        /// </summary>
        internal static string Settings_DockCurrentMediaAction_Option_SwitchToPlayer {
            get {
                return ResourceManager.GetString("Settings_DockCurrentMediaAction_Option_SwitchToPlayer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Choose what happens when you select the current media item in the Dock..
        /// </summary>
        internal static string Settings_DockCurrentMediaAction_Subtitle {
            get {
                return ResourceManager.GetString("Settings_DockCurrentMediaAction_Subtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Current media item action.
        /// </summary>
        internal static string Settings_DockCurrentMediaAction_Title {
            get {
                return ResourceManager.GetString("Settings_DockCurrentMediaAction_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Choose icons for the Command Palette Dock..
        /// </summary>
        internal static string Settings_DockIconTheme_Subtitle {
            get {
                return ResourceManager.GetString("Settings_DockIconTheme_Subtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Icon theme.
        /// </summary>
        internal static string Settings_DockIconTheme_Title {
            get {
                return ResourceManager.GetString("Settings_DockIconTheme_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show this extension&apos;s system volume commands. Turn this off if another extension already provides them..
        /// </summary>
        internal static string Settings_EnableVolumeControls_Subtitle {
            get {
                return ResourceManager.GetString("Settings_EnableVolumeControls_Subtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enable volume controls.
        /// </summary>
        internal static string Settings_EnableVolumeControls_Title {
            get {
                return ResourceManager.GetString("Settings_EnableVolumeControls_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string Settings_GlobalCommands_Option_Disabled {
            get {
                return ResourceManager.GetString("Settings_GlobalCommands_Option_Disabled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string Settings_GlobalCommands_Option_Enabled {
            get {
                return ResourceManager.GetString("Settings_GlobalCommands_Option_Enabled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show additional Media Controls commands in global search results..
        /// </summary>
        internal static string Settings_GlobalCommands_Subtitle {
            get {
                return ResourceManager.GetString("Settings_GlobalCommands_Subtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Additional global commands.
        /// </summary>
        internal static string Settings_GlobalCommands_Title {
            get {
                return ResourceManager.GetString("Settings_GlobalCommands_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Appearance and behavior.
        /// </summary>
        internal static string Settings_Group_AppearanceAndBehavior {
            get {
                return ResourceManager.GetString("Settings_Group_AppearanceAndBehavior", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Commands.
        /// </summary>
        internal static string Settings_Group_Commands {
            get {
                return ResourceManager.GetString("Settings_Group_Commands", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dock.
        /// </summary>
        internal static string Settings_Group_Dock {
            get {
                return ResourceManager.GetString("Settings_Group_Dock", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Help and acknowledgements.
        /// </summary>
        internal static string Settings_Group_HelpAndAcknowledgements {
            get {
                return ResourceManager.GetString("Settings_Group_HelpAndAcknowledgements", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Media sources.
        /// </summary>
        internal static string Settings_Group_MediaBackends {
            get {
                return ResourceManager.GetString("Settings_Group_MediaBackends", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Command Palette page.
        /// </summary>
        internal static string Settings_Group_PalettePage {
            get {
                return ResourceManager.GetString("Settings_Group_PalettePage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to VLC connection.
        /// </summary>
        internal static string Settings_Group_Vlc {
            get {
                return ResourceManager.GetString("Settings_Group_Vlc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [Get help, report a problem, or view the source code](https://github.com/jiripolasek/MediaControlsExtension).
        /// </summary>
        internal static string Settings_Help {
            get {
                return ResourceManager.GetString("Settings_Help", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hide after changing tracks.
        /// </summary>
        internal static string Settings_HideAfterChangingTracks {
            get {
                return ResourceManager.GetString("Settings_HideAfterChangingTracks", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hide after Play/Pause.
        /// </summary>
        internal static string Settings_HideAfterPlayPause {
            get {
                return ResourceManager.GetString("Settings_HideAfterPlayPause", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hide after toggle play/pause on media session.
        /// </summary>
        internal static string Settings_HideAfterTogglePlayPause {
            get {
                return ResourceManager.GetString("Settings_HideAfterTogglePlayPause", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Default ({0}).
        /// </summary>
        internal static string Settings_IconTheme_Default {
            get {
                return ResourceManager.GetString("Settings_IconTheme_Default", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to When pause other players is enabled, starting a remote session can pause other players, and starting any player can pause remote sessions..
        /// </summary>
        internal static string Settings_IncludeRemoteSessionsInPauseOthers_Subtitle {
            get {
                return ResourceManager.GetString("Settings_IncludeRemoteSessionsInPauseOthers_Subtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Include remote sessions when pausing other players.
        /// </summary>
        internal static string Settings_IncludeRemoteSessionsInPauseOthers_Title {
            get {
                return ResourceManager.GetString("Settings_IncludeRemoteSessionsInPauseOthers_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Run multiple media commands in sequence without reopening Command Palette. Hold Shift while running a command to temporarily reverse this behavior..
        /// </summary>
        internal static string Settings_KeepOpen_Subtitle {
            get {
                return ResourceManager.GetString("Settings_KeepOpen_Subtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Keep Command Palette open after a command.
        /// </summary>
        internal static string Settings_KeepOpen_Title {
            get {
                return ResourceManager.GetString("Settings_KeepOpen_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Configure media providers from the Media sources page in Media Controls. Open the Media Controls command menu and choose Media sources..
        /// </summary>
        internal static string Settings_MediaBackends_Help {
            get {
                return ResourceManager.GetString("Settings_MediaBackends_Help", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to When starting a local session, pause other local sessions. Remote sessions participate only when included below..
        /// </summary>
        internal static string Settings_PauseOthersOnPlay_Subtitle {
            get {
                return ResourceManager.GetString("Settings_PauseOthersOnPlay_Subtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pause other sessions when playback starts.
        /// </summary>
        internal static string Settings_PauseOthersOnPlay_Title {
            get {
                return ResourceManager.GetString("Settings_PauseOthersOnPlay_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add a “Now Playing” item for quick access to the current media session..
        /// </summary>
        internal static string Settings_ShowCurrentMediaAtTopLevel_Subtitle {
            get {
                return ResourceManager.GetString("Settings_ShowCurrentMediaAtTopLevel_Subtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show the current media session on the home page.
        /// </summary>
        internal static string Settings_ShowCurrentMediaAtTopLevel_Title {
            get {
                return ResourceManager.GetString("Settings_ShowCurrentMediaAtTopLevel_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open the details pane automatically on the Media Controls page..
        /// </summary>
        internal static string Settings_ShowDetails_Subtitle {
            get {
                return ResourceManager.GetString("Settings_ShowDetails_Subtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show media details by default.
        /// </summary>
        internal static string Settings_ShowDetails_Title {
            get {
                return ResourceManager.GetString("Settings_ShowDetails_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Display “Next Track” and “Previous Track” on the Media Controls page..
        /// </summary>
        internal static string Settings_ShowSkipCommands_Subtitle {
            get {
                return ResourceManager.GetString("Settings_ShowSkipCommands_Subtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show track navigation commands.
        /// </summary>
        internal static string Settings_ShowSkipCommands_Title {
            get {
                return ResourceManager.GetString("Settings_ShowSkipCommands_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Display “Next Track” and “Previous Track” in the Dock..
        /// </summary>
        internal static string Settings_ShowSkipCommandsInDock_Subtitle {
            get {
                return ResourceManager.GetString("Settings_ShowSkipCommandsInDock_Subtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show track navigation commands.
        /// </summary>
        internal static string Settings_ShowSkipCommandsInDock_Title {
            get {
                return ResourceManager.GetString("Settings_ShowSkipCommandsInDock_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Use media thumbnails (album art) instead of app icons in the session list..
        /// </summary>
        internal static string Settings_ShowThumbnails_Subtitle {
            get {
                return ResourceManager.GetString("Settings_ShowThumbnails_Subtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show thumbnails.
        /// </summary>
        internal static string Settings_ShowThumbnails_Title {
            get {
                return ResourceManager.GetString("Settings_ShowThumbnails_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show a notification after each media action..
        /// </summary>
        internal static string Settings_ShowToastMessages_Subtitle {
            get {
                return ResourceManager.GetString("Settings_ShowToastMessages_Subtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show action confirmations.
        /// </summary>
        internal static string Settings_ShowToastMessages_Title {
            get {
                return ResourceManager.GetString("Settings_ShowToastMessages_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show Volume Down and Volume Up in the system volume Dock band..
        /// </summary>
        internal static string Settings_ShowVolumeAdjustmentCommandsInDock_Subtitle {
            get {
                return ResourceManager.GetString("Settings_ShowVolumeAdjustmentCommandsInDock_Subtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show volume adjustment buttons.
        /// </summary>
        internal static string Settings_ShowVolumeAdjustmentCommandsInDock_Title {
            get {
                return ResourceManager.GetString("Settings_ShowVolumeAdjustmentCommandsInDock_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to For example, http://127.0.0.1:8080 or http://living-room:8080. Use the server root, without a path or password..
        /// </summary>
        internal static string Settings_Vlc_Endpoint_Description {
            get {
                return ResourceManager.GetString("Settings_Vlc_Endpoint_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter a valid HTTP or HTTPS server URL with no path, query, fragment, or embedded password..
        /// </summary>
        internal static string Settings_Vlc_Endpoint_Invalid {
            get {
                return ResourceManager.GetString("Settings_Vlc_Endpoint_Invalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Server URL.
        /// </summary>
        internal static string Settings_Vlc_Endpoint_Title {
            get {
                return ResourceManager.GetString("Settings_Vlc_Endpoint_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to In VLC, enable the Web interface and set a Lua HTTP password, then restart VLC. For another computer, allow the interface and firewall to accept connections from this computer. Save its server URL and password below, then use Test saved connection from this page&apos;s command menu. Enable or disable VLC from Media sources. HTTP connections are intended for trusted networks; use HTTPS when your server provides it..
        /// </summary>
        internal static string Settings_Vlc_Help {
            get {
                return ResourceManager.GetString("Settings_Vlc_Help", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Saved in Windows Credential Locker for this server URL. Leave blank to use that server&apos;s saved password. A new server needs its own password..
        /// </summary>
        internal static string Settings_Vlc_Password_Description {
            get {
                return ResourceManager.GetString("Settings_Vlc_Password_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not read the saved VLC password from Windows Credential Locker. Enter the password again and save..
        /// </summary>
        internal static string Settings_Vlc_Password_LoadFailed {
            get {
                return ResourceManager.GetString("Settings_Vlc_Password_LoadFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter or replace the VLC password.
        /// </summary>
        internal static string Settings_Vlc_Password_Placeholder {
            get {
                return ResourceManager.GetString("Settings_Vlc_Password_Placeholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not save the VLC password in Windows Credential Locker. The new password was not applied. Try saving again..
        /// </summary>
        internal static string Settings_Vlc_Password_SaveFailed {
            get {
                return ResourceManager.GetString("Settings_Vlc_Password_SaveFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to HTTP password.
        /// </summary>
        internal static string Settings_Vlc_Password_Title {
            get {
                return ResourceManager.GetString("Settings_Vlc_Password_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Local sessions participate in automatic selection, player switching, and pausing other local players. Automatic treats loopback URLs as local and all other URLs as remote. This choice does not change which local VLC sessions are replaced..
        /// </summary>
        internal static string Settings_Vlc_TreatAsLocal_Description {
            get {
                return ResourceManager.GetString("Settings_Vlc_TreatAsLocal_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Treat this session as local.
        /// </summary>
        internal static string Settings_Vlc_TreatAsLocal_Title {
            get {
                return ResourceManager.GetString("Settings_Vlc_TreatAsLocal_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Automatic (from server URL).
        /// </summary>
        internal static string Settings_Vlc_Treatment_Auto {
            get {
                return ResourceManager.GetString("Settings_Vlc_Treatment_Auto", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Settings_Vlc_Treatment_Local {
            get {
                return ResourceManager.GetString("Settings_Vlc_Treatment_Local", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string Settings_Vlc_Treatment_Remote {
            get {
                return ResourceManager.GetString("Settings_Vlc_Treatment_Remote", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Playing.
        /// </summary>
        internal static string Tags_Playing {
            get {
                return ResourceManager.GetString("Tags_Playing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t change the volume.
        /// </summary>
        internal static string Toast_CantChangeVolume {
            get {
                return ResourceManager.GetString("Toast_CantChangeVolume", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not change repeat mode.
        /// </summary>
        internal static string Toast_CouldNotChangeRepeat {
            get {
                return ResourceManager.GetString("Toast_CouldNotChangeRepeat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not pause playback.
        /// </summary>
        internal static string Toast_CouldNotPause {
            get {
                return ResourceManager.GetString("Toast_CouldNotPause", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not play track.
        /// </summary>
        internal static string Toast_CouldNotPlay {
            get {
                return ResourceManager.GetString("Toast_CouldNotPlay", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not skip to next track.
        /// </summary>
        internal static string Toast_CouldNotSkipNext {
            get {
                return ResourceManager.GetString("Toast_CouldNotSkipNext", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not go to previous track.
        /// </summary>
        internal static string Toast_CouldNotSkipPrevious {
            get {
                return ResourceManager.GetString("Toast_CouldNotSkipPrevious", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not switch to {0}: {1}.
        /// </summary>
        internal static string Toast_CouldNotSwitchTo {
            get {
                return ResourceManager.GetString("Toast_CouldNotSwitchTo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not toggle shuffle.
        /// </summary>
        internal static string Toast_CouldNotToggleShuffle {
            get {
                return ResourceManager.GetString("Toast_CouldNotToggleShuffle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Media controls stopped responding. Restart the extension to retry..
        /// </summary>
        internal static string Toast_MediaControlsUnavailable {
            get {
                return ResourceManager.GetString("Toast_MediaControlsUnavailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Muted.
        /// </summary>
        internal static string Toast_Muted {
            get {
                return ResourceManager.GetString("Toast_Muted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No current media session found.
        /// </summary>
        internal static string Toast_NoCurrentSession {
            get {
                return ResourceManager.GetString("Toast_NoCurrentSession", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No next session found.
        /// </summary>
        internal static string Toast_NoNextSession {
            get {
                return ResourceManager.GetString("Toast_NoNextSession", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No other sessions to switch to.
        /// </summary>
        internal static string Toast_NoOtherSessions {
            get {
                return ResourceManager.GetString("Toast_NoOtherSessions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No media session manager found.
        /// </summary>
        internal static string Toast_NoSessionManager {
            get {
                return ResourceManager.GetString("Toast_NoSessionManager", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Not the current session.
        /// </summary>
        internal static string Toast_NotCurrentSession {
            get {
                return ResourceManager.GetString("Toast_NotCurrentSession", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nothing happened.
        /// </summary>
        internal static string Toast_NothingHappened {
            get {
                return ResourceManager.GetString("Toast_NothingHappened", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nothing is playing.
        /// </summary>
        internal static string Toast_NothingPlaying {
            get {
                return ResourceManager.GetString("Toast_NothingPlaying", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        internal static string Toast_Paused {
            get {
                return ResourceManager.GetString("Toast_Paused", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not pause another player..
        /// </summary>
        internal static string Toast_PauseOtherFailed {
            get {
                return ResourceManager.GetString("Toast_PauseOtherFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not pause {0} other players..
        /// </summary>
        internal static string Toast_PauseOthersFailed {
            get {
                return ResourceManager.GetString("Toast_PauseOthersFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The playback request was canceled because an earlier change could not be confirmed..
        /// </summary>
        internal static string Toast_PlaybackAbandoned {
            get {
                return ResourceManager.GetString("Toast_PlaybackAbandoned", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Playback could not be confirmed..
        /// </summary>
        internal static string Toast_PlaybackUnconfirmed {
            get {
                return ResourceManager.GetString("Toast_PlaybackUnconfirmed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Playing.
        /// </summary>
        internal static string Toast_Playing {
            get {
                return ResourceManager.GetString("Toast_Playing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Playing {0}.
        /// </summary>
        internal static string Toast_PlayingName {
            get {
                return ResourceManager.GetString("Toast_PlayingName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Repeat mode changed to {0}.
        /// </summary>
        internal static string Toast_RepeatChanged {
            get {
                return ResourceManager.GetString("Toast_RepeatChanged", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Repeat control is not available for this session.
        /// </summary>
        internal static string Toast_RepeatNotAvailable {
            get {
                return ResourceManager.GetString("Toast_RepeatNotAvailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Shuffle disabled.
        /// </summary>
        internal static string Toast_ShuffleDisabled {
            get {
                return ResourceManager.GetString("Toast_ShuffleDisabled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Shuffle enabled.
        /// </summary>
        internal static string Toast_ShuffleEnabled {
            get {
                return ResourceManager.GetString("Toast_ShuffleEnabled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Shuffle control is not available for this session.
        /// </summary>
        internal static string Toast_ShuffleNotAvailable {
            get {
                return ResourceManager.GetString("Toast_ShuffleNotAvailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Skipped to next track.
        /// </summary>
        internal static string Toast_SkippedNext {
            get {
                return ResourceManager.GetString("Toast_SkippedNext", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Returned to previous track.
        /// </summary>
        internal static string Toast_SkippedPrevious {
            get {
                return ResourceManager.GetString("Toast_SkippedPrevious", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Switched to {0} and {1}.
        /// </summary>
        internal static string Toast_SwitchedTo {
            get {
                return ResourceManager.GetString("Toast_SwitchedTo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unmuted.
        /// </summary>
        internal static string Toast_Unmuted {
            get {
                return ResourceManager.GetString("Toast_Unmuted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        internal static string Toast_Volume {
            get {
                return ResourceManager.GetString("Toast_Volume", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Toggle Play / Pause.
        /// </summary>
        internal static string TogglePlayPause {
            get {
                return ResourceManager.GetString("TogglePlayPause", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Play or pause current media.
        /// </summary>
        internal static string TogglePlayPause_Comments {
            get {
                return ResourceManager.GetString("TogglePlayPause_Comments", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0}%.
        /// </summary>
        internal static string Volume_Level {
            get {
                return ResourceManager.GetString("Volume_Level", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Volume - {0} %.
        /// </summary>
        internal static string Volume_Status {
            get {
                return ResourceManager.GetString("Volume_Status", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Volume - muted.
        /// </summary>
        internal static string Volume_StatusMuted {
            get {
                return ResourceManager.GetString("Volume_StatusMuted", resourceCulture);
            }
        }
    }
}