//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JPSoftworks.MediaControlsExtension.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JPSoftworks.MediaControlsExtension.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute.
        /// </summary>
        internal static string Command_Mute {
            get {
                return ResourceManager.GetString("Command_Mute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute system volume.
        /// </summary>
        internal static string Command_Mute_Subtitle {
            get {
                return ResourceManager.GetString("Command_Mute_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Application.
        /// </summary>
        internal static string Command_NextApp {
            get {
                return ResourceManager.GetString("Command_NextApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Track.
        /// </summary>
        internal static string Command_NextTrack {
            get {
                return ResourceManager.GetString("Command_NextTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip to the next track in the active media session.
        /// </summary>
        internal static string Command_NextTrack_Subtitle {
            get {
                return ResourceManager.GetString("Command_NextTrack_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string Command_Pause {
            get {
                return ResourceManager.GetString("Command_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string Command_Play {
            get {
                return ResourceManager.GetString("Command_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play / Pause.
        /// </summary>
        internal static string Command_PlayPause {
            get {
                return ResourceManager.GetString("Command_PlayPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Application.
        /// </summary>
        internal static string Command_PreviousApp {
            get {
                return ResourceManager.GetString("Command_PreviousApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Track.
        /// </summary>
        internal static string Command_PreviousTrack {
            get {
                return ResourceManager.GetString("Command_PreviousTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns to the previous track in the active media session.
        /// </summary>
        internal static string Command_PreviousTrack_Subtitle {
            get {
                return ResourceManager.GetString("Command_PreviousTrack_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set volume to {0}%.
        /// </summary>
        internal static string Command_SetVolume {
            get {
                return ResourceManager.GetString("Command_SetVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string Command_Stop {
            get {
                return ResourceManager.GetString("Command_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to Application.
        /// </summary>
        internal static string Command_SwitchToApplication {
            get {
                return ResourceManager.GetString("Command_SwitchToApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle volume mute.
        /// </summary>
        internal static string Command_ToggleMute {
            get {
                return ResourceManager.GetString("Command_ToggleMute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Repeat.
        /// </summary>
        internal static string Command_ToggleRepeat {
            get {
                return ResourceManager.GetString("Command_ToggleRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Shuffle.
        /// </summary>
        internal static string Command_ToggleShuffle {
            get {
                return ResourceManager.GetString("Command_ToggleShuffle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmute.
        /// </summary>
        internal static string Command_Unmute {
            get {
                return ResourceManager.GetString("Command_Unmute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmute system volume.
        /// </summary>
        internal static string Command_Unmute_Subtitle {
            get {
                return ResourceManager.GetString("Command_Unmute_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View full metadata.
        /// </summary>
        internal static string Command_ViewMetadata {
            get {
                return ResourceManager.GetString("Command_ViewMetadata", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Volume down.
        /// </summary>
        internal static string Command_VolumeDown {
            get {
                return ResourceManager.GetString("Command_VolumeDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume up.
        /// </summary>
        internal static string Command_VolumeUp {
            get {
                return ResourceManager.GetString("Command_VolumeUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album.
        /// </summary>
        internal static string Details_Album {
            get {
                return ResourceManager.GetString("Details_Album", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Album artist.
        /// </summary>
        internal static string Details_AlbumArtist {
            get {
                return ResourceManager.GetString("Details_AlbumArtist", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Application ID.
        /// </summary>
        internal static string Details_ApplicationId {
            get {
                return ResourceManager.GetString("Details_ApplicationId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        internal static string Details_Artist {
            get {
                return ResourceManager.GetString("Details_Artist", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Commands.
        /// </summary>
        internal static string Details_Commands {
            get {
                return ResourceManager.GetString("Details_Commands", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Genres.
        /// </summary>
        internal static string Details_Genres {
            get {
                return ResourceManager.GetString("Details_Genres", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        internal static string Details_Length {
            get {
                return ResourceManager.GetString("Details_Length", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Media type.
        /// </summary>
        internal static string Details_MediaType {
            get {
                return ResourceManager.GetString("Details_MediaType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string Details_MediaType_Image {
            get {
                return ResourceManager.GetString("Details_MediaType_Image", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        internal static string Details_MediaType_Music {
            get {
                return ResourceManager.GetString("Details_MediaType_Music", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Details_MediaType_Unknown {
            get {
                return ResourceManager.GetString("Details_MediaType_Unknown", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        internal static string Details_MediaType_Video {
            get {
                return ResourceManager.GetString("Details_MediaType_Video", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Not available.
        /// </summary>
        internal static string Details_NotAvailable {
            get {
                return ResourceManager.GetString("Details_NotAvailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Playback status.
        /// </summary>
        internal static string Details_PlaybackStatus {
            get {
                return ResourceManager.GetString("Details_PlaybackStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        internal static string Details_Player {
            get {
                return ResourceManager.GetString("Details_Player", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Subtitle.
        /// </summary>
        internal static string Details_Subtitle {
            get {
                return ResourceManager.GetString("Details_Subtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Details_Title {
            get {
                return ResourceManager.GetString("Details_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Track.
        /// </summary>
        internal static string Details_TrackNumber {
            get {
                return ResourceManager.GetString("Details_TrackNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} of {1}.
        /// </summary>
        internal static string Details_TrackNumberWithCount {
            get {
                return ResourceManager.GetString("Details_TrackNumberWithCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No media sources are currently available. Please ensure that you have media applications running that support media controls..
        /// </summary>
        internal static string EmptyContent_Subtitle {
            get {
                return ResourceManager.GetString("EmptyContent_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No media sources available.
        /// </summary>
        internal static string EmptyContent_Title {
            get {
                return ResourceManager.GetString("EmptyContent_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage playback and switch between media apps with ease.
        /// </summary>
        internal static string MediaControls_Subtitle {
            get {
                return ResourceManager.GetString("MediaControls_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album artwork.
        /// </summary>
        internal static string Metadata_ArtworkAltText {
            get {
                return ResourceManager.GetString("Metadata_ArtworkAltText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No media metadata is available..
        /// </summary>
        internal static string Metadata_NoMedia {
            get {
                return ResourceManager.GetString("Metadata_NoMedia", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Media metadata.
        /// </summary>
        internal static string Metadata_PageTitle {
            get {
                return ResourceManager.GetString("Metadata_PageTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Metadata.
        /// </summary>
        internal static string Metadata_Section {
            get {
                return ResourceManager.GetString("Metadata_Section", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Technical information.
        /// </summary>
        internal static string Metadata_TechnicalSection {
            get {
                return ResourceManager.GetString("Metadata_TechnicalSection", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Media Controls.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing is playing right now.
        /// </summary>
        internal static string NowPlaying_NothingPlaying {
            get {
                return ResourceManager.GetString("NowPlaying_NothingPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now playing {0}.
        /// </summary>
        internal static string NowPlaying_NowPlaying {
            get {
                return ResourceManager.GetString("NowPlaying_NowPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause {0}.
        /// </summary>
        internal static string NowPlaying_Pause {
            get {
                return ResourceManager.GetString("NowPlaying_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play {0}.
        /// </summary>
        internal static string NowPlaying_Play {
            get {
                return ResourceManager.GetString("NowPlaying_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop {0}.
        /// </summary>
        internal static string NowPlaying_Stop {
            get {
                return ResourceManager.GetString("NowPlaying_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now playing.
        /// </summary>
        internal static string NowPlaying_Subtitle {
            get {
                return ResourceManager.GetString("NowPlaying_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search media commands or sessions….
        /// </summary>
        internal static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by [Jiří Polášek](https://jiripolasek.com)
        ///_Licensed under the Apache 2.0 license_
        ///_Copyright © Jiří Polášek_
        ///
        ///Special thanks to [Mike Griese](https://github.com/zadjii-msft).
        /// </summary>
        internal static string Settings_Acknowledgements {
            get {
                return ResourceManager.GetString("Settings_Acknowledgements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose icons for the Command Palette home page and Media Controls list page..
        /// </summary>
        internal static string Settings_CommandPaletteIconTheme_Subtitle {
            get {
                return ResourceManager.GetString("Settings_CommandPaletteIconTheme_Subtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Icon theme.
        /// </summary>
        internal static string Settings_CommandPaletteIconTheme_Title {
            get {
                return ResourceManager.GetString("Settings_CommandPaletteIconTheme_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Choose icons for the Command Palette Dock..
        /// </summary>
        internal static string Settings_DockIconTheme_Subtitle {
            get {
                return ResourceManager.GetString("Settings_DockIconTheme_Subtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Icon theme.
        /// </summary>
        internal static string Settings_DockIconTheme_Title {
            get {
                return ResourceManager.GetString("Settings_DockIconTheme_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show this extension&apos;s system volume commands. Turn this off if another extension already provides them..
        /// </summary>
        internal static string Settings_EnableVolumeControls_Subtitle {
            get {
                return ResourceManager.GetString("Settings_EnableVolumeControls_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable volume controls.
        /// </summary>
        internal static string Settings_EnableVolumeControls_Title {
            get {
                return ResourceManager.GetString("Settings_EnableVolumeControls_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string Settings_GlobalCommands_Option_Disabled {
            get {
                return ResourceManager.GetString("Settings_GlobalCommands_Option_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string Settings_GlobalCommands_Option_Enabled {
            get {
                return ResourceManager.GetString("Settings_GlobalCommands_Option_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show additional Media Controls commands in global search results..
        /// </summary>
        internal static string Settings_GlobalCommands_Subtitle {
            get {
                return ResourceManager.GetString("Settings_GlobalCommands_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional global commands.
        /// </summary>
        internal static string Settings_GlobalCommands_Title {
            get {
                return ResourceManager.GetString("Settings_GlobalCommands_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance and behavior.
        /// </summary>
        internal static string Settings_Group_AppearanceAndBehavior {
            get {
                return ResourceManager.GetString("Settings_Group_AppearanceAndBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands.
        /// </summary>
        internal static string Settings_Group_Commands {
            get {
                return ResourceManager.GetString("Settings_Group_Commands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dock.
        /// </summary>
        internal static string Settings_Group_Dock {
            get {
                return ResourceManager.GetString("Settings_Group_Dock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help and acknowledgements.
        /// </summary>
        internal static string Settings_Group_HelpAndAcknowledgements {
            get {
                return ResourceManager.GetString("Settings_Group_HelpAndAcknowledgements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Palette page.
        /// </summary>
        internal static string Settings_Group_PalettePage {
            get {
                return ResourceManager.GetString("Settings_Group_PalettePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Get help, report a problem, or view the source code](https://github.com/jiripolasek/MediaControlsExtension).
        /// </summary>
        internal static string Settings_Help {
            get {
                return ResourceManager.GetString("Settings_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide after changing tracks.
        /// </summary>
        internal static string Settings_HideAfterChangingTracks {
            get {
                return ResourceManager.GetString("Settings_HideAfterChangingTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide after Play/Pause.
        /// </summary>
        internal static string Settings_HideAfterPlayPause {
            get {
                return ResourceManager.GetString("Settings_HideAfterPlayPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide after toggle play/pause on media session.
        /// </summary>
        internal static string Settings_HideAfterTogglePlayPause {
            get {
                return ResourceManager.GetString("Settings_HideAfterTogglePlayPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default ({0}).
        /// </summary>
        internal static string Settings_IconTheme_Default {
            get {
                return ResourceManager.GetString("Settings_IconTheme_Default", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Run multiple media commands in sequence without reopening Command Palette. Hold Shift while running a command to temporarily reverse this behavior..
        /// </summary>
        internal static string Settings_KeepOpen_Subtitle {
            get {
                return ResourceManager.GetString("Settings_KeepOpen_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Command Palette open after a command.
        /// </summary>
        internal static string Settings_KeepOpen_Title {
            get {
                return ResourceManager.GetString("Settings_KeepOpen_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When playing a session, automatically pause all other sessions..
        /// </summary>
        internal static string Settings_PauseOthersOnPlay_Subtitle {
            get {
                return ResourceManager.GetString("Settings_PauseOthersOnPlay_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause other sessions when playback starts.
        /// </summary>
        internal static string Settings_PauseOthersOnPlay_Title {
            get {
                return ResourceManager.GetString("Settings_PauseOthersOnPlay_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a “Now Playing” item for quick access to the current media session..
        /// </summary>
        internal static string Settings_ShowCurrentMediaAtTopLevel_Subtitle {
            get {
                return ResourceManager.GetString("Settings_ShowCurrentMediaAtTopLevel_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the current media session on the home page.
        /// </summary>
        internal static string Settings_ShowCurrentMediaAtTopLevel_Title {
            get {
                return ResourceManager.GetString("Settings_ShowCurrentMediaAtTopLevel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the details pane automatically on the Media Controls page..
        /// </summary>
        internal static string Settings_ShowDetails_Subtitle {
            get {
                return ResourceManager.GetString("Settings_ShowDetails_Subtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show media details by default.
        /// </summary>
        internal static string Settings_ShowDetails_Title {
            get {
                return ResourceManager.GetString("Settings_ShowDetails_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Display “Next Track” and “Previous Track” on the Media Controls page..
        /// </summary>
        internal static string Settings_ShowSkipCommands_Subtitle {
            get {
                return ResourceManager.GetString("Settings_ShowSkipCommands_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show track navigation commands.
        /// </summary>
        internal static string Settings_ShowSkipCommands_Title {
            get {
                return ResourceManager.GetString("Settings_ShowSkipCommands_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display “Next Track” and “Previous Track” in the Dock..
        /// </summary>
        internal static string Settings_ShowSkipCommandsInDock_Subtitle {
            get {
                return ResourceManager.GetString("Settings_ShowSkipCommandsInDock_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show track navigation commands.
        /// </summary>
        internal static string Settings_ShowSkipCommandsInDock_Title {
            get {
                return ResourceManager.GetString("Settings_ShowSkipCommandsInDock_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use media thumbnails (album art) instead of app icons in the session list..
        /// </summary>
        internal static string Settings_ShowThumbnails_Subtitle {
            get {
                return ResourceManager.GetString("Settings_ShowThumbnails_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show thumbnails.
        /// </summary>
        internal static string Settings_ShowThumbnails_Title {
            get {
                return ResourceManager.GetString("Settings_ShowThumbnails_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show a notification after each media action..
        /// </summary>
        internal static string Settings_ShowToastMessages_Subtitle {
            get {
                return ResourceManager.GetString("Settings_ShowToastMessages_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show action confirmations.
        /// </summary>
        internal static string Settings_ShowToastMessages_Title {
            get {
                return ResourceManager.GetString("Settings_ShowToastMessages_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing.
        /// </summary>
        internal static string Tags_Playing {
            get {
                return ResourceManager.GetString("Tags_Playing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t change the volume.
        /// </summary>
        internal static string Toast_CantChangeVolume {
            get {
                return ResourceManager.GetString("Toast_CantChangeVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not change repeat mode.
        /// </summary>
        internal static string Toast_CouldNotChangeRepeat {
            get {
                return ResourceManager.GetString("Toast_CouldNotChangeRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not pause playback.
        /// </summary>
        internal static string Toast_CouldNotPause {
            get {
                return ResourceManager.GetString("Toast_CouldNotPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not play track.
        /// </summary>
        internal static string Toast_CouldNotPlay {
            get {
                return ResourceManager.GetString("Toast_CouldNotPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not skip to next track.
        /// </summary>
        internal static string Toast_CouldNotSkipNext {
            get {
                return ResourceManager.GetString("Toast_CouldNotSkipNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not go to previous track.
        /// </summary>
        internal static string Toast_CouldNotSkipPrevious {
            get {
                return ResourceManager.GetString("Toast_CouldNotSkipPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not switch to {0}: {1}.
        /// </summary>
        internal static string Toast_CouldNotSwitchTo {
            get {
                return ResourceManager.GetString("Toast_CouldNotSwitchTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not toggle shuffle.
        /// </summary>
        internal static string Toast_CouldNotToggleShuffle {
            get {
                return ResourceManager.GetString("Toast_CouldNotToggleShuffle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media controls stopped responding. Restart the extension to retry..
        /// </summary>
        internal static string Toast_MediaControlsUnavailable {
            get {
                return ResourceManager.GetString("Toast_MediaControlsUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muted.
        /// </summary>
        internal static string Toast_Muted {
            get {
                return ResourceManager.GetString("Toast_Muted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No current media session found.
        /// </summary>
        internal static string Toast_NoCurrentSession {
            get {
                return ResourceManager.GetString("Toast_NoCurrentSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No next session found.
        /// </summary>
        internal static string Toast_NoNextSession {
            get {
                return ResourceManager.GetString("Toast_NoNextSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No other sessions to switch to.
        /// </summary>
        internal static string Toast_NoOtherSessions {
            get {
                return ResourceManager.GetString("Toast_NoOtherSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No media session manager found.
        /// </summary>
        internal static string Toast_NoSessionManager {
            get {
                return ResourceManager.GetString("Toast_NoSessionManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not the current session.
        /// </summary>
        internal static string Toast_NotCurrentSession {
            get {
                return ResourceManager.GetString("Toast_NotCurrentSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing happened.
        /// </summary>
        internal static string Toast_NothingHappened {
            get {
                return ResourceManager.GetString("Toast_NothingHappened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing is playing.
        /// </summary>
        internal static string Toast_NothingPlaying {
            get {
                return ResourceManager.GetString("Toast_NothingPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        internal static string Toast_Paused {
            get {
                return ResourceManager.GetString("Toast_Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing.
        /// </summary>
        internal static string Toast_Playing {
            get {
                return ResourceManager.GetString("Toast_Playing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing {0}.
        /// </summary>
        internal static string Toast_PlayingName {
            get {
                return ResourceManager.GetString("Toast_PlayingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat mode changed to {0}.
        /// </summary>
        internal static string Toast_RepeatChanged {
            get {
                return ResourceManager.GetString("Toast_RepeatChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat control is not available for this session.
        /// </summary>
        internal static string Toast_RepeatNotAvailable {
            get {
                return ResourceManager.GetString("Toast_RepeatNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuffle disabled.
        /// </summary>
        internal static string Toast_ShuffleDisabled {
            get {
                return ResourceManager.GetString("Toast_ShuffleDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuffle enabled.
        /// </summary>
        internal static string Toast_ShuffleEnabled {
            get {
                return ResourceManager.GetString("Toast_ShuffleEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuffle control is not available for this session.
        /// </summary>
        internal static string Toast_ShuffleNotAvailable {
            get {
                return ResourceManager.GetString("Toast_ShuffleNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped to next track.
        /// </summary>
        internal static string Toast_SkippedNext {
            get {
                return ResourceManager.GetString("Toast_SkippedNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returned to previous track.
        /// </summary>
        internal static string Toast_SkippedPrevious {
            get {
                return ResourceManager.GetString("Toast_SkippedPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switched to {0} and {1}.
        /// </summary>
        internal static string Toast_SwitchedTo {
            get {
                return ResourceManager.GetString("Toast_SwitchedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmuted.
        /// </summary>
        internal static string Toast_Unmuted {
            get {
                return ResourceManager.GetString("Toast_Unmuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        internal static string Toast_Volume {
            get {
                return ResourceManager.GetString("Toast_Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Play / Pause.
        /// </summary>
        internal static string TogglePlayPause {
            get {
                return ResourceManager.GetString("TogglePlayPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play or pause current media.
        /// </summary>
        internal static string TogglePlayPause_Comments {
            get {
                return ResourceManager.GetString("TogglePlayPause_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}%.
        /// </summary>
        internal static string Volume_Level {
            get {
                return ResourceManager.GetString("Volume_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume - {0} %.
        /// </summary>
        internal static string Volume_Status {
            get {
                return ResourceManager.GetString("Volume_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume - muted.
        /// </summary>
        internal static string Volume_StatusMuted {
            get {
                return ResourceManager.GetString("Volume_StatusMuted", resourceCulture);
            }
        }
    }
}
