<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<RuntimeIdentifiers>$(CmdPalRuntimeIdentifiers)</RuntimeIdentifiers>
		<IsAotCompatible>true</IsAotCompatible>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
		<PackageReference Include="Microsoft.Windows.CsWinRT" />
	</ItemGroup>
</Project>
